### ISSUE TITLE
installation plateforme stt

### ISSUE THREAD

**Issue by eli-tail** [linto-ai/linto-stt#21]
Hi, 
I'm currently trying to install the platform set tool via your documentation through docker image. 

First I've pulled the depo and tried to build but it seems there is an issue with Kaldi. 

```
#7 17.99 configure: error: in `/opt/kaldi/tools/openfst-1.8.0':
#7 17.99 configure: error: Test float equality failed! Compile with -msse -mfpmath=sse if using g++.
#7 17.99 See `config.log' for more details
#7 18.02 make: *** [Makefile:85: openfst-1.8.0/Makefile] Error 1
```

Then I switched to the already built docker image and followed the steps described [here](https://doc.linto.ai/docs/developpers/apis/ASR/docker) well no chance either. 
1. The .env it is said to set: SERVING_MODE=http but there is no SERVING_MODE, I supposed we need to CHANGE SERVICE_MODE to SERVING_MODE ? => this is what I did but the error remains: 

`ERROR: Must specify a serving mode: [ http | task | websocket ]
`
2. I have an error about the model : 
```
Model type not specified, expecting Vosk Model
Using Vosk format's model
```
For this option I kept the "lin" option that is set up in the original .env, I also tried to set up a vosk model manually but didn't work either. 

Do you have any tips to fix these issues ? 

On an other topic, I've seen for the later stages that there is a broker to set up ? 
I test this tool as a data scientist and would like some further advice to set this up completely. 

Regards 
Eli

**Comment by eli-tail** [comment]
Hi, any news / help on this ?

**Comment by Jeronymous** [comment]
Concerning "SERVING_MODE", yes it is a typo in the README. Please use SERVICE_MODE.

Concerning the "MODEL_TYPE" env variable, it's weird... Can you share the `.env` file you use?
It should look like the .envdefault that is given:
```
# SERVING PARAMETERS
SERVICE_MODE=http
MODEL_TYPE=lin
...
```
and then you should run the docker container with `[docker run] --env-file .env ...`.
Unless you want to pass environment variable in another way (then share what you pass).

Concerning the installation issues, I'm missing some details to understand.
You have this error when running `docker build .` in the git folder? Is there a way to see what's in the `config.log` mentioned in the error message?

In general, for these problems I recommend that you join the ["LinTO Community" on Discord](https://discord.gg/jvNK3FXv3d). 
This is the good place to get advice to set up a broker?
And there is a `#issues-and-bugs` channel for your issues, where people should be responsive.
